# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/osx-64/blas-1.0-mkl.conda
https://conda.anaconda.org/anaconda/osx-64/ca-certificates-2019.11.27-0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/intel-openmp-2019.4-233.conda
https://repo.anaconda.com/pkgs/main/osx-64/libcxxabi-4.0.1-hcfea43d_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/libgfortran-3.0.1-h93005f0_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/yaml-0.1.7-hc338f04_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/zlib-1.2.11-h1de35cc_3.conda
https://repo.anaconda.com/pkgs/main/osx-64/libcxx-4.0.1-hcfea43d_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/mkl-2019.4-233.conda
https://repo.anaconda.com/pkgs/main/osx-64/tk-8.6.8-ha441bb4_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/geos-3.8.0-h0a44026_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libffi-3.2.1-h475c297_4.conda
https://repo.anaconda.com/pkgs/main/osx-64/ncurses-6.1-h0a44026_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/libedit-3.1.20181209-hb402a30_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/readline-7.0-h1de35cc_5.conda
https://repo.anaconda.com/pkgs/main/osx-64/sqlite-3.30.1-ha441bb4_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/python-2.7.17-h97142e2_0.conda
https://conda.anaconda.org/anaconda/osx-64/atomicwrites-1.3.0-py27_1.tar.bz2
https://conda.anaconda.org/anaconda/noarch/attrs-19.3.0-py_0.tar.bz2
https://conda.anaconda.org/anaconda/noarch/backports-1.0-py_2.tar.bz2
https://conda.anaconda.org/anaconda/osx-64/certifi-2019.11.28-py27_0.tar.bz2
https://conda.anaconda.org/anaconda/noarch/contextlib2-0.6.0.post1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/faulthandler-3.1-py27h1de35cc_0.conda
https://conda.anaconda.org/anaconda/osx-64/funcsigs-1.0.2-py27hb9f6266_0.tar.bz2
https://conda.anaconda.org/anaconda/noarch/py-1.8.1-py_0.tar.bz2
https://conda.anaconda.org/anaconda/noarch/pyparsing-2.4.6-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pytz-2019.3-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pyyaml-5.1.1-py27h1de35cc_0.conda
https://conda.anaconda.org/anaconda/osx-64/scandir-1.10.0-py27h1de35cc_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/six-1.13.0-py27_0.tar.bz2
https://conda.anaconda.org/anaconda/osx-64/wcwidth-0.1.7-py27h817c265_0.tar.bz2
https://conda.anaconda.org/anaconda/osx-64/configparser-4.0.2-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/mkl-service-2.3.0-py27hfbe908c_0.conda
https://conda.anaconda.org/anaconda/osx-64/more-itertools-5.0.0-py27_0.tar.bz2
https://conda.anaconda.org/anaconda/noarch/packaging-20.0-py_0.tar.bz2
https://conda.anaconda.org/anaconda/osx-64/pathlib2-2.3.5-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/setuptools-41.6.0-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/cython-0.29.14-py27h0a44026_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/numpy-base-1.16.5-py27h6575580_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/wheel-0.33.6-py27_0.tar.bz2
https://conda.anaconda.org/anaconda/noarch/zipp-0.6.0-py_0.tar.bz2
https://conda.anaconda.org/anaconda/osx-64/importlib_metadata-1.3.0-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pip-19.3.1-py27_0.tar.bz2
https://conda.anaconda.org/anaconda/osx-64/pluggy-0.13.1-py27_0.tar.bz2
https://conda.anaconda.org/anaconda/osx-64/pytest-4.6.2-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/mkl_fft-1.0.15-py27h5e564d8_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/mkl_random-1.1.0-py27ha771720_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/numpy-1.16.5-py27hacdab7b_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pandas-0.24.2-py27h0a44026_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/scipy-1.2.1-py27h1410ff5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/shapely-1.6.4-py27h6e5b138_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/scikit-learn-0.20.3-py27h27c97d8_0.conda
